services:
  d_application_api.database_helpers:
    class: Drupal\d_application_api\Database\DatabaseHelpers
  d_application_api.features:
    class: Drupal\d_application_api\Helpers\Features
  d_application_api.event_subscriber:
      class: Drupal\d_application_api\EventSubscriber\EventSubscriber
      arguments: []
      tags:
        - {name: event_subscriber}

  d_application_api.clear_cache:
      class: Drupal\d_application_api\Helpers\ClearCache
